FROM jenkins/jenkins:lts

USER root

# Install Docker CLI, python3-venv, and make
RUN apt-get update && \
    apt-get install -y docker.io python3-venv make && \
    rm -rf /var/lib/apt/lists/*

USER jenkins